site_name: Tasmota
site_description: Documentation (Wiki) for Tasmota. Open source firmware for ESP8266 devices with easy configuration using webUI, OTA updates, automation using timers or rules, expandability and entirely local control over MQTT, HTTP, serial or KNX.
site_url: https://tasmota.github.io/docs/
repo_name: 'arendst/tasmota'
repo_url: 'https://github.com/arendst/tasmota'
edit_uri: 'https://github.com/tasmota/docs/blob/master/docs/'
# copyright: 'Copyright &copy; 2020 Tasmota Development Team'
# use_directory_urls: false

strict: true

theme: 
  name: material
  # custom_dir: 'theme'
  logo: '_media/logo.svg'
  favicon: _media/favicon.ico
  palette:
    primary: 'blue'
    accent: 'indigo'
  features:
    - tabs
  font:
    text: Barlow
    code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/discord
      link: 'https://discord.gg/Ks2Kzd4'
    - icon: fontawesome/brands/telegram
      link: 'https://t.me/tasmota'
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/tasmota'
markdown_extensions:
  - admonition
  - toc:
     permalink: "~"
     toc_depth: 3
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.emoji:
  - pymdownx.betterem
  - pymdownx.caret
  - codehilite
  - meta
      
plugins:
  - search
  - alternate-link
  - minify:
      minify_html: true
  # - htmlproofer

google_analytics:
  - 'UA-140681905-2'
  - 'auto'

extra_css:
  - 'assets/css/anchor-fix.css'

nav: 
  - Home: index.md
  - About.md
  - Getting Started: Getting-Started.md
  - Upgrading.md
  - MQTT.md
  - Commands: Commands.md
  - Templates: Templates.md
  - Components.md
  - Modules: Modules.md
  - Peripherals: Peripherals.md
  - WebUI.md
  - Features:
    - Introduction: Features.md
    - Buttons-and-Switches.md
    - Device-Groups.md
    - Lights.md
    - PIR-Motion-Sensors.md
    - Power-Monitoring-Calibration.md
    - PWM-dimmer-switch.md
    - Rules.md
    - Blinds-and-Shutters.md
    - Timers.md
    - TuyaMCU.md
    - Bluetooth.md
    - Zigbee.md
    - IR Communication: Tasmota-IR.md
    - DeepSleep.md
    - Dynamic-Sleep.md
    - I2C Devices: I2CDevices.md
    - Scripting: Scripting-Language.md
    - Smart-Meter-Interface.md
    - TasmotaSlave.md
    - Subscribe-&-Unsubscribe.md
    - TLS.md
    - Tutorials.md
    - For Developers: For-Developers.md
  - Smart Home Integrations:
    - Introduction: Integrations.md
    - Alexa.md
    - AWS-IoT.md
    - Domoticz.md
    - Home-Assistant.md
    - Homebridge.md
    - HomeSeer.md
    - IP-Symcon.md
    - KNX.md
    - NodeRed.md
    - nymea.md
    - Octoprint.md
    - openHAB.md
    - otto.md
    - IOBroker: "https://github.com/arendst/Tasmota/issues/3769"
    - Mozilla WebThings Adapter: "https://github.com/tim-hellhake/tasmota-adapter"
    - SmartThings: "https://github.com/BrettSheleski/SmartThingsPublic/tree/master/devicetypes/brettsheleski/sonoff-tasmota.src"
  - Peripherals:
    - Supported-Peripherals.md
    - Analog pin: ADC.md
    - Buzzer.md
    - Displays:
      - Displays.md
    - A4988 stepper motor controller: A4988-Stepper-Motor-Controller.md
    - AM2301 temperature and humidity sensor: AM2301.md
    - APDS-9960.md
    - AZ-7798.md
    - BH1750.md
    - BME280.md
    - BME680.md
    # - Buzzer.md
    - CC2530.md
    - Chirp! moisture sensor: Moisture-Sensor-and-Chirp!-Sensor.md
    - DHT11.md
    - DS18x20.md
    - DS3231.md
    - HM-10.md
    - HM-17.md
    - HC-SR04.md
    - Honeywell-HIH.md
    - IR-Remote.md
    - LM75AD.md
    - MCP230xx.md
    - MGC3130.md
    - MH-Z19B.md
    - MLX90614.md
    - MPR121.md
    - MPU-6050.md
    - NRF24L01.md
    - P1-Smart-Meter.md
    - PAJ7620.md
    - PCA9685.md
    - PN532.md
    - PZEM-0XX.md
    - RCWL-0516.md
    - RDM6300.md
    - SDS011.md
    - SHT30.md
    - TX2x.md
    - TSL2561.md
    - VEML6070.md
    - VL53L0x.md
    - WS2812B-RGB-Shield.md
    - WS2812B-and-WS2813.md
  - Supported Devices:
    - Configuring unknown devices: Configuration-Procedure-for-New-Devices.md
    - All Supported Devices: https://templates.blakadder.com/ "target=_blank"
    - Supported-Modules.md
  - Help:
    - FAQ.md
    - Troubleshooting.md
    - Device-Recovery.md
    - Discord Support: http://thehackbox.org/tasmota/release/ "target=_blank"
  - Compiling: Compile-your-build.md
  - Contributing: Contributing.md
  - Download: http://thehackbox.org/tasmota/release/ "target=_blank"
